version: '3.8'

networks:
  bridge:
    driver: bridge

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=nestjs
      - POSTGRES_USER=nestjs
      - POSTGRES_PASSWORD=nestjs
    networks:
      - bridge
